version: '3'
services:
  chipplayerjs-nginx:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    image: soltune/chipplayerjs-nginx
    ports:
      - "5000:80"
      - "5001:5001"
    volumes:
      - www:/var/www/
      - catalog:/var/www/static/catalog/
    stdin_open: true
    tty: true
    command: [nginx, '-g', 'daemon off;']

  chipplayerjs-node:
    build:
      context: .
      dockerfile: ./Dockerfile-node
    image: soltune/chipplayerjs-node
    expose:
      - "8080"
    volumes:
      - www:/usr/share/www/
    stdin_open: true
    tty: true
    working_dir: /usr/share/www/
    command: [node, 'index.js']


volumes:
  www:
    driver_opts:
      type: none
      device: ${PWD}/../www
      o: bind
  catalog:
    driver_opts:
      type: none
      device: ${PWD}/../catalog
      o: bind

